//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore_App2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public long business_id { get; set; }
        public long customer_id { get; set; }
        public string vat_number { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
